config/routes.rb
Rails.application.routes.draw do

  root to: "public/posts#index"

  get "/home/about" => "homes#about"

  devise_for :members, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
}

  devise_for :admins, skip: [:passwords, :registrations] ,controllers: {
  sessions: "admin/sessions"
}

# ゲストメンバー
   devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#guest_sign_in'
  end


  scope module: :public do
    resources :posts, only: [:new,:index,:show,:create,:edit,:update,:destroy] do
      resource :bookmark, only: [:destroy,:create]
      resources :reviews, only: [:index,:create,:update,:destroy]
      resources :post_comments, only: [:create,:destroy]
    end
    resources :members, only: [:show, :edit, :update] do
      member do
        get :bookmarks
        # 退会確認画面
        get 'members/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
        # 論理削除用のルーティング
        patch 'members/withdraw' => 'members#withdraw', as: 'withdraw'
      end
    end
      # タグに紐づいた投稿一覧を表示（タグの詳細ページ）
      resources :tags, only: [:show]
  end

  namespace :admin do
    resources :members, only: [:index,:show,:edit,:update]
    resources :posts, only: [:index,:show,:destroy] do
      resources :reviews, only: [:index,:destroy]
      resources :post_comments, only: [:destroy]
    end
     resources :tags, only: [:show]
  end

end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :member
  belongs_to :post
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :email, presence: true
  validates :name, presence: true

  # ゲストメンバー設定
  def self.guest
    # 条件を指定して初めの1件を取得し1件もなければ作成
    find_or_create_by!(name: 'guestmember' ,email: 'guest@example.com') do |member|
      # ランダムで URL-safe(URLとして扱える) な base64 (64進数でできた)文字列を生成して返す
      member.password = SecureRandom.urlsafe_base64
      member.name = "guestmember"
    end
  end

  # is_activeがtrueならfalseを返す（退会ユーザーはログインできないようにする）
  def active_for_authentication?
    is_active == true
  end

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  belongs_to :member

  # 都道府県コードから県名を変換するgem(jp_prefecture)を読み込む
  include JpPrefecture

  # タグのリレーション
  has_many :tag_posts, dependent: :destroy  #tagsとの中間テーブル
  has_many :tags, through: :tag_posts, dependent: :destroy


  # 退会中のメンバーの投稿が表示されてしまうため、入会中のメンバーの投稿のみ表示されるようにする
  scope :is_active, -> { includes(:member).where(members: {is_active: true}) }
  # includes　postsテーブルとmembers: {is_active: true}をつなげる
  # includesメソッドで指定された関連付けが最小限のクエリ回数で読み込まれ、
  # これによってN+1問題(mysql上に多量のデータが保存されてしまう問題)が解決される

  # 上記は、以下と同義。->はdef〜endの役割
  # def self.is_active
  #   self.includes(:member).where(members: {is_active: true})
  # end


  validates :name, presence: true
  validates :address, presence: true
  validates :url, presence: true
  validates :phone_number, presence: true
  validates :opening_hour, presence: true
  validates :prefecture, presence: true

  # 住所（addressカラム）を入れたときに、自動で緯度、経度をlatitude,longitudeカラムに記述
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_one_attached :image


  def get_image(width,height)
    unless image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit:[width,height]).processed
  end

  # 指定したブックマークが存在するかどうか
  def bookmarked_by?(member)
    bookmarks.exists?(member_id: member.id)
  end

  #ブックマークボタンの条件分岐で使用
  def bookmarked(member)
    bookmarks.find_by(member_id: member.id)
  end

  def save_tag(sent_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil? #pulckで指定したレコードの配列を取得
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

  # 検索機能で使用→posts_controller.erbのindexアクションに記載
  # def self.looks(word)
  #   Post.where("name LIKE?","%#{word}%")
  # end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  # save直前にメソッドを呼ぶ
   before_save :set_star_value

  belongs_to :member
  belongs_to :post

  validates :comment, presence: true

  # レビューのスターがnilであれば、０を代入する
  def set_star_value
      self.star = 0 if self.star.nil?
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_posts, dependent: :destroy, foreign_key: 'tag_id'
  # タグは複数の投稿を持ち、post_tagsを通じて参照できる
  has_many :posts, through: :tag_posts

  validates :name, uniqueness: true

end

app/models/tag_post.rb
class TagPost < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  validates :post_id, presence: true
  validates :tag_id, presence: true

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def show
    #検索結果画面でもタグ一覧表示
    @tag_list = Tag.all
    #検索されたタグを受け取る
    @tag = Tag.find(params[:id])
    @tag.posts
    #検索されたタグに紐づく投稿を表示
    @posts=@tag.posts.is_active.page(params[:page]).per(7)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # https時セキュリティ対策
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about

  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/comments/_comment.html.erb
<div class="ml-5 mt-5">
  <p id="commentsCount">
    <b>レビュー件数:<%= post.post_comments.count %></b>
  </p>
</div>
<!--コメント一覧-->
<table class="table">
  <% post.post_comments.each_with_index do |post_comment, idx| %>
    <tr>
      <td><%= post_comment.member.name %></td>
      <td><%= post_comment.created_at.strftime('%Y/%m/%d') %></td>
      <td id="star-rate-<%= idx + 1 %>"></td>
      <script>
        var elem = document.getElementById("star-rate-<%= idx + 1 %>");
        var opt = {
          size      : 36,
          starOn  : '<%= asset_path('star-on.png') %>',
          starOff : '<%= asset_path('star-off.png') %>',
          //half  : false, (trueだと星半分も表示できる。カラムをfloat型にする必要あり)
          readOnly: true,
          score: <%= post_comment.star %>
        }
        elem.innerHTML=""
        raty(elem, opt);
      </script>
      <td><%= post_comment.comment %></td>
        <td>
          <%= link_to "削除", admin_post_post_comment_path(post_comment.post, post_comment), method: :delete, remote: true, class: "btn btn-danger" %>
        </td>
    </tr>
  <% end %>
</table>
 <!--フラッシュメッセージ-->
<div id="flash-message">
  <%= render 'layouts/flash' %>
</div>

app/views/admin/comments/create.js.erb
$("#comment_<%= @post.id %>").html("<%= j(render "admin/comments/comment", post: @post, post_comment: @post_comment_new) %>");
$('#commentsCount').html('<b>コメント件数:<%= j(@post.post_comments.count) %></b>');
var score = <%= j(@post.post_comments.present? ? @post.post_comments.sum(:star) / @post.post_comments.count : 0) %>
$('#star-rate').empty();
$('#avg').html(`評価 : ${score}点`);
  var elem = document.getElementById("star-rate");
  var opt = {
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    half      : false,
    readOnly: true,
    score: score,
  }
  raty(elem, opt);
$("textarea").val('');

app/views/admin/comments/destroy.js.erb
$("#comment_<%= @post.id %>").html("<%= j(render "admin/comments/comment", post: @post, post_comment: @post_comment) %>");
$('#commentsCount').html('<b>コメント件数:<%= j(@post.post_comments.count) %></b>');
var score = <%= j(@post.post_comments.present? ? @post.post_comments.sum(:star) / @post.post_comments.count : 0) %>
$('#star-rate').empty();
$('#avg').html(`評価 : ${score}点`);
  var elem = document.getElementById("star-rate");
  var opt = {
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    half      : false,
    readOnly: true,
    score: score,
  }
  raty(elem, opt);

app/views/admin/comments/error.js.erb
$("#post-comments-error").html("<div>aaaa</div>");

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h3>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h3>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/admin/shared/_raty_script.html.erb
<script>
  var elem = document.getElementById(element_id);
  var opt = {
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    half      : false,
    readOnly  : true,
    score: <%= score %>,
  }
  // 再読み込みする際、星が増えないようにする
  // （再読み込み前の星の空文字にする）
  elem.innerHTML=""
  raty(elem, opt);
</script>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      <h5><%= model.errors.count %>件のエラー</h5>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<!--コメント部分のフラッシュメッセージ-->
<div style="text-align: center;">
<% flash.each do |message_type, message| %>
  <% case message_type %>
    <% when 'notice' then %>
      <p class="alert alert-success"><%= message %></p>
    <% when 'alert' then %>
      <p class="alert alert-danger"><%= message %></p>
  <% end %>
<% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <div style="text-align: center;">
    <p><small>&copy;2022 SSS</small></p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <% if admin_signed_in? %>
    <a class="navbar-brand ml-5" href="/admin/posts"><%= image_tag 'logo.png', class: "logo", height: 65 %><a>
  <% else %>
    <a class="navbar-brand ml-5" href="/"><%= image_tag 'logo.png', class: "logo", height: 65 %><a>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="#navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <div class="ml-5">
      <% if member_signed_in? %>
        <b>ようこそ！
          <br><%= current_member.name %>さん
        </b>
      <% elsif admin_signed_in? %>
        <b>管理者ログイン中</b>
      <% end %>
    </div>
    <ul class="navbar-nav ml-auto mr-3 mt-2 mt-lg-0">
      <% if member_signed_in? %>
        <li class="mr-2">
          <%= link_to "投稿フォーム", new_post_path, class: "btn btn-secondary" %>
        </li>
        <li class="mx-2">
          <%= link_to "マイページ", member_path(current_member), class: "btn btn-secondary" %>
        </li>
        <li class="mx-2">
          <%= link_to "ブックマーク一覧", bookmarks_member_path(current_member), class: "btn btn-secondary" %>
        </li>
        <li class="mx-2">
          <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: "btn btn-secondary" %>
        </li>
        <!--検索フォーム-->
      <div class="form-inline my-2 my-lg-0 search_form">
        <%= render 'public/posts/search' %>
      </div>
      <% elsif admin_signed_in? %>
        <li class="mr-2">
          <%= link_to "About", home_about_path, class: "btn btn-secondary" %>
        </li>
        <li class="mx-2">
          <%= link_to "会員一覧", admin_members_path, class: "btn btn-secondary" %>
        </li>
        <li class="mx-2">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-secondary" %>
        </li>
        <!--検索フォーム-->
      <div class="form-inline my-2 my-lg-0 search_form">
        <%= render 'admin/posts/search' %>
      </div>
      <% else %>
         <li class="mr-2">
          <%= link_to "About", home_about_path, class: "btn btn-secondary" %>
        </li>
        <li class="mx-2">
          <%= link_to "新規登録", new_member_registration_path, class: "btn btn-secondary" %>
        </li>
        <li class="mx-2">
          <%= link_to "ログイン", new_member_session_path, class: "btn btn-secondary" %>
        </li>
        <!--検索フォーム-->
        <li class="form-inline my-2 my-lg-0 search_form">
          <%= render 'public/posts/search' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SSS</title>
    <meta name = "viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "mb-auto">
    <header class="shadow-sm" style = "background-color: #87cefa;"><%= render 'layouts/header' %></header>
        <!--フラッシュメッセージ-->
        <% unless controller_name == "post_comments" %>
          <div style = "text-align: center;">
            <% if flash[:notice] %>
              <p class = "alert alert-success"><%= notice %></p>
            <% elsif flash[:alert] %>
              <p class = "alert alert-danger"><%= alert %></p>
            <% end %>
          </div>
        <% end %>
        <%= yield %>
    <footer class = "bg-dark pt-5 pb-4"><%= render 'layouts/footer' %></footer>
  </body>
</html>