config/routes.rb
Rails.application.routes.draw do

  root to: "public/posts#index"

  get "/home/about" => "homes#about"

  devise_for :members, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
}

  devise_for :admins, skip: [:passwords, :registrations] ,controllers: {
  sessions: "admin/sessions"
}

# ゲストメンバー
   devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#guest_sign_in'
  end


  scope module: :public do
    resources :posts, only: [:new,:index,:show,:create,:edit,:update,:destroy] do
      resource :bookmark, only: [:destroy,:create]
      resources :reviews, only: [:index,:create,:update,:destroy]
      resources :post_comments, only: [:create,:destroy]
    end
    resources :members, only: [:show, :edit, :update] do
      member do
        get :bookmarks
        # 退会確認画面
        get 'members/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
        # 論理削除用のルーティング
        patch 'members/withdraw' => 'members#withdraw', as: 'withdraw'
      end
    end
      # タグに紐づいた投稿一覧を表示（タグの詳細ページ）
      resources :tags, only: [:show]
  end

  namespace :admin do
    resources :members, only: [:index,:show,:edit,:update]
    resources :posts, only: [:index,:show,:destroy] do
      resources :reviews, only: [:index,:destroy]
      resources :post_comments, only: [:destroy]
    end
     resources :tags, only: [:show]
  end

end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :email, presence: true
  validates :name, presence: true

  # ゲストメンバー設定
  def self.guest
    # 条件を指定して初めの1件を取得し1件もなければ作成
    find_or_create_by!(name: 'guestmember' ,email: 'guest@example.com') do |member|
      # ランダムで URL-safe(URLとして扱える) な base64 (64進数でできた)文字列を生成して返す
      member.password = SecureRandom.urlsafe_base64
      member.name = "guestmember"
    end
  end

  # is_activeがtrueならfalseを返す（退会ユーザーはログインできないようにする）
  def active_for_authentication?
    is_active == true
  end

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @members = Member.page(params[:page]).per(10)
  end

  def show
    @member = Member.find(params[:id])
    @posts=@member.posts.page(params[:page]).per(7)
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
       redirect_to admin_member_path, notice: "ユーザー情報を更新しました"
    else
       flash.now[:alert] = "項目を入力してください"
       render 'edit'
    end
  end

  private

  def member_params
    params.require(:member).permit(:name ,:encrypted_password, :email, :is_active)
  end
end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
  def guest_sign_in
    member = Member.guest
    sign_in member
    redirect_to root_path, notice: 'ゲストメンバーでログインしました。'
  end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/edit.html.erb
<div class="container my-5" style="box-sizing: content-box; min-height: 60vh;">
  <div class="col-9 px-4 ml-5 my-4">
    <div class="row">
      <h2 class="px-3"><%= @member.name %>さんの会員情報編集</h2>
    </div>
  　　　　　　　　　　　　<!--情報更新するのでupdate_path-->
    <%= form_with model: @member, url: admin_member_path(@member), method: :patch do |f| %>
      <table class="table table-borderless ml-5">
        <tr>
          <td style="width: 270px;">ユーザーネーム</td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td style="width: 270px;">メールアドレス</td>
          <td><%= f.text_field :email %></td>
        </tr>
        <tr>
          <td style="width: 270px;">会員ステータス</td>
          <td>
            <% if @member.is_active == true %>
              <%= f.radio_button :is_active, true, checked: true %>
              <%= f.label :is_active, "有効" %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, "退会" %>
            <% else %>
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, "有効" %>
              <%= f.radio_button :is_active, false, checked: true %>
              <%= f.label :is_active, "退会" %>
            <% end %>
          </td>
        </tr>
      </table>
      <div class="my-5 ml-5">
        <p style="text-align: center;">
          <%= f.submit "編集内容を保存", class: "btn btn-success mr-3" %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/members/index.html.erb
<div class="container text-center my-5" style="box-sizing: content-box; min-height: 60vh;">
  <div class="row mb-4">
    <div class="col-4 pl-5">
      <div class="row mx-5">
        <h2 class="px-3">会員一覧</h2>
      </div>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class ="col-sm-9">
      <table class="table table-hover">
        <thead>
          <tr class="active">
            <th class="col-2">会員ID</th>
            <th>ユーザーネーム</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @members.each do |member| %>
          <tr>
            <td>
              <%= member.id %>
            </td>
            <td>
              <%= link_to admin_member_path(member) do %>
                <%= member.name %>
              <% end %>
            </td>
            <td>
              <%= member.email %>
            </td>
            <td>
              <% if member.is_active == true %>
                <p>有効</p>
              <% else %>
                <p>退会</p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="ml-3"><%= paginate @members %></div>
    </div>
  </div>
</div>

app/views/admin/members/show.html.erb
<div class="container my-5">
  <div class="row my-4 ml-5 px-5">
    <h2 class="px-3"><%= @member.name %>さんの会員情報</h2>
  </div>
    <div class="mb-4">
      <div class="col-9 ml-5 mx-5 pl-5">
        <div class="ml-1 px-5">
          <div class="row my-4">
            <h4 class="px-3"><b>登録情報</b></h4>
          </div>
            <table class="table table-bordered shadow">
              <tr>
                <td class="col-3" style="background-color: #e9e9e9;">ユーザーネーム</td>
                <td style="background-color: #fff;"><%= @member.name %></td>
              </tr>
              <tr>
                <td style="background-color: #e9e9e9;">メールアドレス</td>
                <td style="background-color: #fff;"><%= @member.email %></td>
              </tr>
              <tr>
                <td style="background-color: #e9e9e9;">会員ステータス</td>
                <td style="background-color: #fff;">
                  <% if @member.is_active == true %>
                    有効
                  <% else %>
                    退会
                  <% end %>
                </td>
              </tr>
            </table>
            <div class="mt-2">
              <p style="text-align: end;">
                <%= link_to "ユーザー情報編集", edit_admin_member_path(@member), class: "btn btn-success" %>
              </p>
            </div>
        </div>
      </div>
      <div class="ml-5 px-5">
          <div class="m-5 pr-3 mb-0">
            <div class="row my-4">
              <h4 class="px-3"><b><%= @member.name %>さんの投稿一覧</b></h4>
            </div>
               <% if @posts.empty? %>
                  <div class="mt-5 mr-5 pr-3 mb-0">
                     <h3 class="text-center"><b>投稿はありません</b></h3>
                  </div>
               <% else %>
                 <div class="mt-5 mr-5 pr-3 mb-0">
                   <% @posts.each do |post| %>
                     <table class="table table-bordered bg-light shadow">
                       <tr>
                         <td class="lead">
                           <b>
                             <%= link_to admin_post_path(post) do %>
                               <%= post.name %>
                             <% end %>
                           </b>
                         </td>
                       </tr>
                       <tr>
                         <td><%= post.address %></td>
                       </tr>
                       <tr>
                         <td><%= image_tag post.get_image(300,300), style: "border-radius: 10px"; %></td>
                       </tr>
                       <tr>
                         <td>
                           <p class="mb-0"><%= post.post_comments.count %>件の評価</p>
                           <p id="star-rate-<%= post.id %>"></p>
                           <% count = post.post_comments.size %>
                           <% score = count != 0 ? (post.post_comments.sum(:star) / post.post_comments.size) : 0 %>
                         </td>
                       </tr>
                       <!--５段階評価のscript-->
                       <%= render "admin/shared/raty_script", element_id: "star-rate-#{post.id}", score: score %>
                       <script>
                         var elem = document.getElementById("star-rate-<%= post.id %>");
                         var opt = {
                           size      : 36,
                           starOff   : '<%= asset_path('star-off.png') %>',
                           starOn    : '<%= asset_path('star-on.png') %>',
                           half      : false,
                           readOnly: true,
                           score: <%= score %>,
                          }
                          // 再読み込みする際、星が増えないようにする
                          // （再読み込み前の星の空文字にする）
                          elem.innerHTML=""
                          raty(elem, opt);
                        </script>
                       <tr>
                         <td class="sentiment-score">説明文の感情分析スコア：<b><%= post.score %></b></td>
                       </tr>
                       <!--タグリスト-->
                       <tr style="height: 3rem;">
                         <td>
                           <% post.tags.each do |tag| %>
                             <%= link_to tag.name, admin_tag_path(tag) %>
                             <%= "(#{tag.posts.is_active.count})" %>
                           <% end %>
                         </td>
                       </tr>
                    </table>
                  <% end %>
               <%= paginate @posts %>
               </div>
            <% end %>
         </div>
       </div>
    </div>
</div>