config/routes.rb
Rails.application.routes.draw do

  root to: "public/posts#index"

  get "/home/about" => "homes#about"

  devise_for :members, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
}

  devise_for :admins, skip: [:passwords, :registrations] ,controllers: {
  sessions: "admin/sessions"
}

# ゲストメンバー
   devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#guest_sign_in'
  end


  scope module: :public do
    resources :posts, only: [:new,:index,:show,:create,:edit,:update,:destroy] do
      resource :bookmark, only: [:destroy,:create]
      resources :reviews, only: [:index,:create,:update,:destroy]
      resources :post_comments, only: [:create,:destroy]
    end
    resources :members, only: [:show, :edit, :update] do
      member do
        get :bookmarks
        # 退会確認画面
        get 'members/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
        # 論理削除用のルーティング
        patch 'members/withdraw' => 'members#withdraw', as: 'withdraw'
      end
    end
      # タグに紐づいた投稿一覧を表示（タグの詳細ページ）
      resources :tags, only: [:show]
  end

  namespace :admin do
    resources :members, only: [:index,:show,:edit,:update]
    resources :posts, only: [:index,:show,:destroy] do
      resources :reviews, only: [:index,:destroy]
      resources :post_comments, only: [:destroy]
    end
     resources :tags, only: [:show]
  end

end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/post.rb
class Post < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  belongs_to :member

  # 都道府県コードから県名を変換するgem(jp_prefecture)を読み込む
  include JpPrefecture

  # タグのリレーション
  has_many :tag_posts, dependent: :destroy  #tagsとの中間テーブル
  has_many :tags, through: :tag_posts, dependent: :destroy


  # 退会中のメンバーの投稿が表示されてしまうため、入会中のメンバーの投稿のみ表示されるようにする
  scope :is_active, -> { includes(:member).where(members: {is_active: true}) }
  # includes　postsテーブルとmembers: {is_active: true}をつなげる
  # includesメソッドで指定された関連付けが最小限のクエリ回数で読み込まれ、
  # これによってN+1問題(mysql上に多量のデータが保存されてしまう問題)が解決される

  # 上記は、以下と同義。->はdef〜endの役割
  # def self.is_active
  #   self.includes(:member).where(members: {is_active: true})
  # end


  validates :name, presence: true
  validates :address, presence: true
  validates :url, presence: true
  validates :phone_number, presence: true
  validates :opening_hour, presence: true
  validates :prefecture, presence: true

  # 住所（addressカラム）を入れたときに、自動で緯度、経度をlatitude,longitudeカラムに記述
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_one_attached :image


  def get_image(width,height)
    unless image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit:[width,height]).processed
  end

  # 指定したブックマークが存在するかどうか
  def bookmarked_by?(member)
    bookmarks.exists?(member_id: member.id)
  end

  #ブックマークボタンの条件分岐で使用
  def bookmarked(member)
    bookmarks.find_by(member_id: member.id)
  end

  def save_tag(sent_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil? #pulckで指定したレコードの配列を取得
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

  # 検索機能で使用→posts_controller.erbのindexアクションに記載
  # def self.looks(word)
  #   Post.where("name LIKE?","%#{word}%")
  # end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.is_active.page(params[:page]).per(7)
    @posts = @posts.where("posts.name LIKE ?", "%#{params[:word]}%") if params[:word].present?
    @posts = @posts.where(prefecture: params[:prefecture]) if params[:prefecture].present?
    @tag_list = Tag.all
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    if @post.post_comments.present?
      @reviews_avg_score = @post.post_comments.sum(:star) / @post.post_comments.count
    else
      @reviews_avg_score = 0
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, alert: "投稿を削除しました"
  end

  private
  def post_params
    params.require(:post).permit(:member_id, :name, :address, :longitude, :latitude, :url, :phone_number, :opening_hour, :description, :prefecture, :image)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_map.html.erb
<div class="map mt-2">
  <div id="map">
  </div>
</div>
  <script>
    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: <%= post.latitude %>, lng: <%= post.longitude %>},
        zoom: 15,
      });

      (function(){
        marker = new google.maps.Marker({
          position:{lat: <%= post.latitude %>, lng: <%= post.longitude %>},
          map: map,
        });
      })();
    }
  </script>
    <!--.envファイル にAPIキーを記述-->
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>

app/views/admin/posts/_search.html.erb
<%= form_with url: admin_posts_path, method: :get, class: "search_container" do |f| %>
  <%= f.text_field :word, value: params[:word], class: "search_form-word", placeholder: "投稿検索" %><%= f.collection_select :prefecture, JpPrefecture::Prefecture.all, :name, :name, { include_blank: '都道府県' }, { class: 'custom-select' } %>
  <button type="submit">
    <i class="fas fa-search"></i>
  </button>
<% end %>


<!--↑下二つを組み合わせ-->


<!--記事から-->
<!--<form method="get" action="" class="search_container">-->
<!--    <input type="text" placeholder="投稿検索">-->
<!--    <button type="submit">-->
<!--        <i class="fas fa-search"></i>-->
<!--    </button>-->
<!--</form>-->

<!--自作-->
<%#= form_with url: root_path, method: :get do |f| %>
  <%#= f.text_field :word, value: params[:word], class: "form-control search_form-word" %>
  <%#= f.submit "投稿検索", class: "btn btn-primary" %>
<%# end %>

app/views/admin/posts/index.html.erb
<div class="container my-5" style="box-sizing: content-box; min-height: 60vh;">
  <div class="row my-4 px-5">
    <h2 class="px-3">投稿一覧</h2>
  </div>
    <div class="row">
      <!--部分テンプレート化するか-->
      <div class="col-2 my-4">
      <!--  <div>-->
      <!--    <h5>カテゴリ</h5>-->
      <!--  </div>-->
      <!--  <div>-->
      <!--    <h5>地域</h5>-->
      <!--  </div>-->
      </div>
      <div class="col-9">
         <% if @posts.empty? %>
            <div class="mt-5 mr-5 pr-3 mb-0">
               <h3 class="text-center"><b>投稿が見つかりませんでした</b></h3>
            </div>
         <% else %>
           <div class="mt-5 mr-5 pr-3 mb-0">
           <% @posts.each do |post| %>
            <table class="table table-bordered bg-light shadow">
              <tr>
                <td class="lead">
                  <b>
                    <%= link_to admin_post_path(post) do %>
                      <%= post.name %>
                    <% end %>
                  </b>
                </td>
                <!--ブックマークボタン-->
                <!--<td style="width: 70px;" align="center" id="bookmark_buttons_<%#= post.id %>">-->
                <!--  <%#= render 'admin/bookmarks/bookmark', post: post %>-->
                <!--<td>-->
              </tr>
              <tr>
                <td><%= post.address %></td>
              </tr>
              <tr>
                <td><%= image_tag post.get_image(300,300), style: "border-radius: 10px"; %></td>
              </tr>
              <tr>
                <td class="pb-0">
                  <p class="mb-0"><%= post.post_comments.count %>件の評価</p>
                  <p id="star-rate-<%= post.id %>"></p>
                  <% count = post.post_comments.size %>
                  <% score = count != 0 ? (post.post_comments.sum(:star) / post.post_comments.size) : 0 %>
                </td>
              </tr>
              <tr>
                <td class="sentiment-score">説明文の感情分析スコア：<b><%= post.score %></b></td>
              </tr>
              <!--５段階評価のscript-->
                <script>
                  var elem = document.getElementById("star-rate-<%= post.id %>");
                  var opt = {
                    size      : 36,
                    starOff   : '<%= asset_path('star-off.png') %>',
                    starOn    : '<%= asset_path('star-on.png') %>',
                    half      : false,
                    readOnly: true,
                    score: <%= score %>,
                  }
                  // 再読み込みする際、星が増えないようにする
                  // （再読み込み前の星の空文字にする）
                  elem.innerHTML=""
                  raty(elem, opt);
                </script>
              <!--タグリスト-->
              <tr style="height: 3rem;">
                <td>
                  <% post.tags.each do |tag| %>
                    <%= link_to tag.name, admin_tag_path(tag) %>
                    <%= "(#{tag.posts.is_active.count})" %>
                  <% end %>
                </td>
              </tr>
            </table>
         　 <% end %>
         　<%= paginate @posts %>
         　</div>
         <% end %>
      </div>
    </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container my-5">
  <div class="row my-4 ml-5 px-5">
    <h2 class="px-3">投稿詳細</h2>
  </div>
    <div class="row ml-2">
      <div class="col-10">
        <div class="ml-5 px-5">
          <table class="table ml-5">
              <tr>
                <td><b>施設名</b></td>
                <td><%= @post.name %></td>
                <!--ブックマークボタン-->
                <!--<td id="bookmark_buttons_<%#= @post.id %>">-->
                <!--  <%#= render 'public/bookmarks/bookmark', post: @post %>-->
                <!--</td>-->
                <td></td>
              </tr>
              <tr>
                <td id="avg">
                  <b><%= @post.post_comments.count %>件の評価</b>
                </td>
                <td id="star-rate" colspan="2"></td>
              </tr>
              <tr>
                <td><b>住所・地図</b></td>
                <td>
                  <%= @post.address %>
                  <!--googlemap-->
                  <%= render 'map', post: @post %>
                </td>
                <td></td>
              </tr>
              <tr>
                <td><b>画像</b></td>
                <td><%= image_tag @post.get_image(300,300), style: "border-radius: 10px"; %></td>
                <td></td>
              </tr>
              <tr>
                <td><b>電話番号</b></td>
                <td><%=  @post.phone_number %></td>
                <td></td>
              </tr>
              <tr>
                <td><b>営業時間</b></td>
                <td><%= @post.opening_hour %></td>
                <td></td>
              </tr>
              <tr>
                <td><b>URL</b></td>
                <td><%= @post.url %></td>
                <td></td>
              </tr>
              <tr>
                <td><b>説明</b></td>
                <td>
                  <%= @post.description %></br></br>
                  <span class="sentiment-score">感情分析スコア：<b><%= @post.score %></b></span>
                </td>
                <td></td>
              </tr>
              <tr>
                <td><b>タグ</b></td>
                <td>
                  <!--タグ-->
                  <% @post.tags.each do |tag| %>
                    <%= link_to tag.name, admin_tag_path(tag) %>
                    <%= "(#{tag.posts.is_active.count})" %>
                  <% end %>
                </td>
                <td></td>
              </tr>
              <tr>
                <td><b>投稿ユーザー</b></td>
                <td>
                  <%= link_to admin_member_path(@post.member) do %>
                    <%= @post.member.name %>
                  <% end %>
                </td>
                <td></td>
              </tr>
              <tr>
                <td><b>投稿日</b></td>
                <td><%= @post.created_at.strftime('%Y/%m/%d') %></td>
                <td></td>
              </tr>
          </table>
          <p class="mt-2" style="text-align: end;">
            <%= link_to "投稿削除", admin_post_path(@post), method: :delete, class: "btn btn-danger" %>
          </p>
          <!--レビュー・コメント部分-->
          <div class="ml-5" id="comment_<%= @post.id %>">
            <%= render 'admin/comments/comment', post: @post, post_comment: @post_comment %>
          </div>
      </div>
    </div>
  </div>
</div>
<script>
  var elem = document.getElementById("star-rate");
  var opt = {
    size      : 36,
    starOff   : '<%= asset_path('star-off.png') %>',
    starOn    : '<%= asset_path('star-on.png') %>',
    half      : false,
    readOnly  : true,
    score: <%= @reviews_avg_score %>,
  }
  // 再読み込みする際、星が増えないようにする
  // （再読み込み前の星の空文字にする）
  elem.innerHTML=""
  raty(elem, opt);
</script>